server:
  port: 8761
  servlet:
    context-path: /admin
spring:
  application:
    name: site-eureka
  boot:
    admin:
      context-path: /admin
      url: /admin
      ui:
        title: Liana6
      client:
        url: http://localhost:8761/admin
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
