server:
  port: 8761
spring:
  application:
    name: site-eureka
  boot:
    admin:
      context-path: admin
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-u-r-l-context: /

logging:
  level:
    root: info
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
