server:
  port: 8050

spring:
  application:
    name: site-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth
          uri: lb://SITE-AUTH
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: service
          uri: lb://SITE-SERVICE
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: debug
