server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: site-auth
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    encoding: utf-8

logging:
  level:
    root: info
