server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: site-auth
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
